### ISSUE TITLE
Where to place the ```build/``` directory in normal (non docker) install at deployment ?

### ISSUE THREAD

**Issue by cedric2080** [alice-lg/alice-lg#103]
Hi,

- I could build the binary for alice-lg (from tag 5.1.1)
- I deployed it (/opt/alice-lg/alice-lg/bin + symlink in /usr/bin) alongside a .conf (/etc/alice-lg)
- I configured a systemd service

However, I am stuck on this issue:
```
● alice-lg.service - Alice Looking Glass
     Loaded: loaded (/etc/systemd/system/alice-lg.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-10-24 15:19:51 UTC; 1s ago
    Process: 18794 ExecStart=/opt/alice-lg/alice-lg/bin/alice-lg-linux-amd64 (code=exited, status=1/FAILURE)
   Main PID: 18794 (code=exited, status=1/FAILURE)
        CPU: 24ms

Oct 24 15:19:51 alice alice-lg-linux-amd64[18794]:   *****      **     **      **    ***     *  ****    *
Oct 24 15:19:51 alice alice-lg-linux-amd64[18794]:  *   ****    ** *   *** *   *** *  *******    *******
Oct 24 15:19:51 alice alice-lg-linux-amd64[18794]: *     **      **     ***     ***    *****      *****
Oct 24 15:19:51 alice alice-lg-linux-amd64[18794]: *
Oct 24 15:19:51 alice alice-lg-linux-amd64[18794]:  **
Oct 24 15:19:51 alice alice-lg-linux-amd64[18794]: 2022/10/24 15:19:51 Using configuration: /etc/alice-lg/alice.conf
Oct 24 15:19:51 alice alice-lg-linux-amd64[18794]: 2022/10/24 15:19:51 Preparing and installing assets
Oct 24 15:19:51 alice alice-lg-linux-amd64[18794]: 2022/10/24 15:19:51 open build/index.html: file does not exist
Oct 24 15:19:51 alice systemd[1]: alice-lg.service: Main process exited, code=exited, status=1/FAILURE
Oct 24 15:19:51 alice systemd[1]: alice-lg.service: Failed with result 'exit-code'.
```

My question: please, where to copy the build/ (containing the website part, statics, etc.) directory I obtained after building alice-lg ?

I was potentially expecting some parameter to change in the .conf, but could not find anything. Any reference in the golang sources seems to be related maybe to the root of the programm ? Do we have to deploy being some server (gunicorn ?) that would serve the build/ files ?

**Comment by cedric2080** [comment]
I have the impression that on the branch "develop", you changed a bit the directory pattern, and possibly architecture, of your app. I will give it a try :)

**Comment by annikahannig** [comment]
Hej! Thanks for the fix!

I was a bit swamped with other projects. I'll tend to this this week.

**Comment by cedric2080** [comment]
Hi @annikahannig 
Looks now good for that issue with the upcoming v6.0.0. Binary can be built with with node 16.18.0 and is launching properly.
Thanks for the update.

Did not launch yet the test suite as I have no postgres on the build machine, as of now.

**Comment by annikahannig** [comment]
Glad to hear this. :)

I'll tag 6.0.0 as soon I can confirm everything works as expected.

There is a development / testing docker compose for a postgres in ./db

With this the test suite should just work.

**Comment by annikahannig** [comment]
The tests are also now run in a CI workflow...

https://github.com/alice-lg/alice-lg/actions
