### ISSUE TITLE
Display timestamp/age of prefix/network learned in Network view

### ISSUE THREAD

**Issue by Inrin** [alice-lg/alice-lg#121]
BIRD shows the time a network is learned:
```
BIRD 2.0.10 ready.
Table master4:
193.0.14.0/24        unicast [R48_16 2023-12-08 09:30:15] * (100) [AS25152i]
        via 185.1.48.16 on eth1
                     unicast [R48_6 2023-12-12 15:39:03] (100) [AS25152i]
        via 185.1.48.6 on eth1
                     unicast [R48_7 2023-12-11 09:18:40] (100) [AS25152i]
        via 185.1.48.7 on eth1
```
Using birdwatcher the timestamp above is propagted with `age`.

Currently the time a network is learned is not visible in the UI:
![image](https://github.com/alice-lg/alice-lg/assets/2144966/f8d860ec-5447-4b51-a3fa-0f03c134d569)
![image](https://github.com/alice-lg/alice-lg/assets/2144966/53db8c3c-5b95-4903-9ede-99479161f0be)

Making it impossible to see the "prefer older" tiebreaker in the best path selection.
Adding the timestamp to the "Network" view would solve this issue.

The `age` (`imported.routes[0].age`) from the API might be a candidate for this.
Although it's not a straight UNIX timestamp from a first glance.

TiA!

**Comment by annikahannig** [comment]
Done.
