### ISSUE TITLE
Problem with Front Page search bar

### ISSUE THREAD

**Issue by moshivji** [alice-lg/alice-lg#124]
Hi
I would like to open an  case for a problem we are seeing on the latest version of AliceLG.

WE have noticed an issue when using the search bar on the front page for looking up a prefix etc. We see this issue over 2 different devices using Alice.

Attached is a  video provided by the customer that shows the issue if this helps ?

https://github.com/alice-lg/alice-lg/assets/26763308/a942d9dc-030a-4865-827b-d456280a33ca

A customer provided some debug for us and they saw some JS errors and the output is also attached. 

![MicrosoftTeams-image (2)](https://github.com/alice-lg/alice-lg/assets/26763308/0c13b6f9-7c64-493f-a43f-4fc618acee57)

**Comment by annikahannig** [comment]
Oh maybe your config is not yet updated?

The spelling of `neighbor` was fixed everywhere and in the `routes_colums` there might be an old `neighbour.asn`.
