### ISSUE TITLE
Consider setting the default branch to `develop`

### ISSUE THREAD

**Issue by jof** [alice-lg/alice-lg#145]
It seems that most active changes and submissions land in the `develop` branch.

Perhaps consider setting `develop` to be the default branch of this repository so that new Pull Requests target the correct branch for contributions?

**Comment by jof** [comment]
That is good guidance, and a reasonable choice.

I'll just continue to base proposed changes on top of `develop`

**Comment by annikahannig** [comment]
Ok :)

Also I wanted to say that I really appreciate your contributions!
I'm just going through the PRs.

**Comment by jof** [comment]
Yay, Open Source Software! 🦈 🎉
