### ISSUE TITLE
Error making Alice

### ISSUE THREAD

**Issue by sistemasnixval** [alice-lg/alice-lg#2]
Hi! Thanks a lot for the project, It's very interesting and useful. 

We get problems compiling the source after cloning repo. 

If we compile the old one ([https://github.com/ecix/alice-lg]) all works without problem. 

FYI.

**Comment by mhannig** [comment]
Hi! 

Can you maybe give me some hints on where the process fails, or what steps you did, so I can reproduce this?

**Comment by mhannig** [comment]
Hi! Sorryt - somehow I lost this issue and somehow could not find it.

I'll have a look :)

**Comment by mhannig** [comment]
I've stopped building the client directly with the tools on my machine and migrated to using docker for this:

I suggest using this build method for now:
```
cd client/
make -f Makefile.docker client_prod

cd ../backend/

make prod
```

**Comment by mhannig** [comment]
Again - Sorry for the late response.

**Comment by mhannig** [comment]
The 'p' is part of the response alice retrieves from the birdwatcher. (Yeah - I know - a bit missleading / unhelpful)

**Comment by mhannig** [comment]
can you check the output of the birdwatcher for:

http://<my_birdwatcher>/routes/dump

Maybe check, that this endpoint is enabled in the birdwatcher config :)

**Comment by sistemasnixval** [comment]
Thanks Matthias!!

Module route_dump was disabled..  :(

Other question about routes filtered, in my Looking Glass when click in neighbour with routes filtered don't show me routes filtered:

https://lg.nixval.com/alice/routeservers/0/protocols/R_199312/routes

However in home search they appear:

https://lg.nixval.com/alice/search?&q=as199312&sources=0&asns=199312&large_communities=57542:65666:20#routes-filtered

Any more features than enable in alice.conf ?

Thanks for your help?

**Comment by mhannig** [comment]
Have you checked if the 
    
     routes_filtered
     routes_noexport

Endpoints are enabled in the `birdwatcher.conf`? :)

**Comment by mhannig** [comment]
Maybe try accessing the birdwatcher with:

     http://<my_birdwatcher_0>/routes/filtered/R_199312

**Comment by sistemasnixval** [comment]
We have this modules enabled in birdwatcher:

```
2018/11/27 10:55:52 Starting Birdwatcher
2018/11/27 10:55:52             Using: /usr/sbin/birdc
2018/11/27 10:55:52            Listen: 0.0.0.0:29184
2018/11/27 10:55:52    ModulesEnabled:
2018/11/27 10:55:52        - routes_table
2018/11/27 10:55:52        - status
2018/11/27 10:55:52        - protocols_bgp
2018/11/27 10:55:52        - routes_protocol
2018/11/27 10:55:52        - routes_peer
2018/11/27 10:55:52        - routes_filtered
2018/11/27 10:55:52        - routes_noexport
2018/11/27 10:55:52        - routes_dump
2018/11/27 10:55:52    Per Peer Tables: false
```

Checking birdwatcher:

```
# curl 172.16.20.21:29184/routes/filtered/R_199312
{"api":{"Version":"1.11.0","result_from_cache":false,"cache_status":{"orig_ttl":0,"cached_at":{"date":"","timezone_type":"","timezone":""}}},"routes":[],"ttl":"2018-11-27T11:02:15.157651036+01:00"}

```

**Comment by mhannig** [comment]
A `show route all filtered R_199312` is executed.
A `show route filtered protocol 'R_199312' all` should be executed.

I'll fix this later

**Comment by sistemasnixval** [comment]
> Let me see If there is a bug in the birdwatcher.
> 
> You were using this repo: https://github.com/alice-lg/birdwatcher, right?

Yes we are using this repo but repo points to the old one.



> A `show route all filtered R_199312` is executed.

This command don't work:

```
bird> show route all filtered 'R_199312'
IP address expected
```


> A `show route filtered protocol 'R_199312' all` should be executed.
> 
> I'll fix this later

And this command gave us this output:

```
bird> show route filtered protocol 'R_199312' all
154.60.250.0/24    via 213.162.194.33 on ens19 [R_199312 2018-11-27 14:17:07] * (100) [AS199312i]
        Type: BGP unicast univ
        BGP.origin: IGP
        BGP.as_path: 199312
        BGP.next_hop: 213.162.194.33
        BGP.local_pref: 100
        BGP.large_community: (57542, 65666, 20)

[...]
```

**Comment by mhannig** [comment]
Good to hear! I'll update the source later tonight.

**Comment by mhannig** [comment]
Hej! 

I just updated the birdwatcher in:
https://github.com/alice-lg/birdwatcher/

This should fix the missing routes filtered and the missing routes not exported.
Version should now be be: 1.11.0

@sistemasnixval Please check if this helps :)

**Comment by sistemasnixval** [comment]
Hi @mhannig 

Birdwatcher 1.11.0 - Running
Routes filtered are displayed correctly

https://lg.nixval.com/alice/routeservers/0/protocols/R_199312/routes

Thank you very much for your help and support to this project!!

**Comment by mhannig** [comment]
Thanks! :)
Glad to hear it works!

**Comment by sistemasnixval** [comment]
Hi Matthias!

We upgrade the source from the repo, but when we are trying to make files again, fail in the second step. Can you give us some light? Regards!

`cd client/
make -f Makefile.docker client_prod --- This works ok

cd ../backend/
make prod --- This not`

Error:
`[root@LookingGlassPre client]# cd ../backend/
[root@LookingGlassPre backend]# make prod
rm -f rice-box.go
rm -f alice-lg-osx-amd64
rm -f alice-lg-linux-amd64
rice embed-go
make: rice: No se encontró el programa
make: *** [bundle] Error 127`
