### ISSUE TITLE
Issue with uptime on peers & Last Reconfig date/time

### ISSUE THREAD

**Issue by moshivji** [alice-lg/alice-lg#21]
Hi

I wonder if you could help. I have set Alice-LG up and and seeing a issue with my uptime values. It displays 292 years for all peers.

If I change the config to be "Uptime = uptime" in the Alice-LG config I then get a very large epoch value.

Any ideas what could be the issue here ?

Also I am getting a incorrect Last Reconfig date as shown in the a screen show attached. 

Any suggestions would be great.
![Screenshot 2019-06-12 at 15 56 03](https://user-images.githubusercontent.com/26763308/59362582-9be38480-8d2b-11e9-8046-6c202807048d.png)

Thanks

Mo

**Comment by ngoburdhan** [comment]
hi,

did you find an answer to this?  we're seeing the same thing.

**Comment by moshivji** [comment]
Not yet. I did add 

servertime = 2006-01-02T15:04:05Z07:00
servertime_short = 02.01.2006
servertime_ext = Mon, 02 Jan 2006 15:04:05 -0700

to my 'alice.conf' file which gave me a very large number instead in the uptime column.

**Comment by moshivji** [comment]
The following has fixed the uptime issue  and Last Reconfig date .

Added to alice.conf

servertime = 2006-01-02T15:04:05Z07:00
servertime_short = 2006-01-02 15:04:05
servertime_ext = 2006-01-02 15:04:05

**Comment by ngoburdhan** [comment]
yes!  thanks a stack! 👍

**Comment by maximiliandallmair** [comment]
same problem but both does not work:
```
servertime = 2006-01-02T15:04:05Z07:00
servertime_short = 02.01.2006
servertime_ext = Mon, 02 Jan 2006 15:04:05 -0700
```

```
servertime = 2006-01-02T15:04:05Z07:00
servertime_short = 2006-01-02 15:04:05
servertime_ext = 2006-01-02 15:04:05
```
