### ISSUE TITLE
make error No such file or directory: 'install'

### ISSUE THREAD

**Issue by maximiliandallmair** [alice-lg/alice-lg#23]
```
make -C client/ client_prod
make[1]: Entering directory '/root/go/src/github.com/alice-lg/alice-lg/client'
Installing dependencies
yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
make[1]: *** [Makefile:27: deps] Error 1
make[1]: Leaving directory '/root/go/src/github.com/alice-lg/alice-lg/client'
make: *** [Makefile:36: client_prod] Error 2
```

OS is debian 10

**Comment by mhannig** [comment]
do you have yarn installed?

You can use the Makefile.docker in the client for building it using, well, docker.

This is a bit of an inconvenience - I need some more time to get the entire app built using docker.

**Comment by maximiliandallmair** [comment]
works now but how can i access alice?
in console:
Listening on: 192.168.1.70:7340
but if i enter this ip i can not access

how to start alice at startup?

**Comment by maximiliandallmair** [comment]
yarn --version
0.32+git
 yes is installed

**Comment by ctomkow** [comment]
See this stackoverflow post: [https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install](https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install)

Basically, uninstall yarn and cmdtest; then reinstall globally or with npm.

**Comment by annikahannig** [comment]
I'll close this, as the build process for the client has now changed again.
