### ISSUE TITLE
Full support for multiple ASNs

### ISSUE THREAD

**Issue by johannesmoos** [alice-lg/alice-lg#28]
At DE-CIX we use different RS ASNs for different locations but all RS are queried by a single Alice instance. RS ASN is set with `asn = 6695`

While it is possible (but does not really scale in case of many Communities and different RS ASNs) to use e.g.

`65501:1101:3 = Bogon prefix (RFC1918 network)`
`65502:1101:3 = Bogon prefix (RFC1918 network)`
`65502:1101:3 = Bogon prefix (RFC1918 network)`

and so on this does (for example) not apply to the `[rpki]` section.

Full support could be implemented by allowing multiple RS ASNs:
`asn = { 65501, 65502, 65503, ... }`

The ASN should not need to be specified in e.g.
`65501:1101:3 = Bogon prefix (RFC1918 network)`

**Comment by annikahannig** [comment]
Next release will support variable expansion.
