### ISSUE TITLE
Consistent route server IDs

### ISSUE THREAD

**Issue by johannesmoos** [alice-lg/alice-lg#3]
The route server IDs configured in the config differ from the IDs used in the URL/API.

Configuration:
```
[source.42]
name = rs1.my.ixp
...
[source.42.birdwatcher]
...
```

If this is the first RS, it is referred to with ID 0 (and so on):

UI: https://lg.my.ixp/alice/routeservers/0
API: https://lg.my.ixp/api/v1/routeservers/0/status

Would be nice if the ID from the config is used - for the example config above, it should look like this:

UI: https://lg.my.ixp/alice/routeservers/42
API: https://lg.my.ixp/api/v1/routeservers/42/status

**Comment by mhannig** [comment]
This should work now.

The ID is a string, so you can even do something like:
```
[source.rs1-muc-v4]
name = rs1.my.ixp
...
[source.rs1-muc-v4.birdwatcher]
...
```
