### ISSUE TITLE
Problem with TLS

### ISSUE THREAD

**Issue by diditonf** [alice-lg/alice-lg#39]
I'm trying run Alice-LG an i'm getting the following error 

2020/08/28 02:48:19 could not load tls cert: open : no such file or directory

There is any way to disable TLS ?

**Comment by dylancmds** [comment]
Having this issue as well, running alice in an ubuntu container. 

`root@e9e4a60ba418:/home/go/src/github.com/alice-lg/alice-lg# ./bin/alice-lg-linux-amd64
        **        ***               Alice 4.2.0
     *****         ***      *
    *  ***          **     ***      Listening on: 127.0.0.1:80
       ***          **      *       Routeservers: 1
      *  **         **
      *  **         **    ***        ****       ***
     *    **        **     ***      * ***  *   * ***
     *    **        **      **     *   ****   *   ***
    *      **       **      **    **         **    ***
    *********       **      **    **         ********
   *        **      **      **    **         *******
   *        **      **      **    **         **
  *****      **     **      **    ***     *  ****    *
 *   ****    ** *   *** *   *** *  *******    *******
*     **      **     ***     ***    *****      *****
*
 **
2020/10/22 12:07:38 Using configuration: /etc/alice-lg/alice.conf
2020/10/22 12:07:38 Starting local routes store
2020/10/22 12:07:38 Routes Store refresh interval set to: 5m0s
2020/10/22 12:07:38 Starting local neighbours store
2020/10/22 12:07:38 Neighbours Store refresh interval set to: 5m0s
2020/10/22 12:07:38 Preparing and installing assets
2020/10/22 12:07:38 could not load tls cert: open : no such file or directory
root@e9e4a60ba418:/home/go/src/github.com/alice-lg/alice-lg#`

**Comment by dylancmds** [comment]
Figured this out myself, add the following line to your goBGP source in alice.conf
`insecure = true`

It would be incredibly helpful to have better documentation on the configuration and the available flags, I had to look through .go source files to figure this out.

**Comment by annikahannig** [comment]
I updated the readme and example config :)

Thanks :+1:
