### ISSUE TITLE
make communities accept lists as input

### ISSUE THREAD

**Issue by stefanplug** [alice-lg/alice-lg#46]
for example:

asn = [1234, 5678, 8787]
...
asn:1101:1 = Prefix is to long (>24 or >64)
asn:1101:2 = Prefix too short
asn:1101:3 = An IP Bogon was detected

**Comment by johannesmoos** [comment]
+1

This will be very very useful when dealing with multiple/many route server ASNs.

**Comment by stefanplug** [comment]
Jep, this indeed looks like a duplicate!
