### ISSUE TITLE
global route search problems

### ISSUE THREAD

**Issue by stefanplug** [alice-lg/alice-lg#67]
We are seeing that sometime for some of our routeservers the cache doesn't seem to be updated/loaded which means that the global prefix search doesn't work.

It seems to be specific per routeserver as a prefix which we is known on 2 separate routeserver might be found on 1 but not the other, as if the cache of the other routeserver is not loaded somehow?

I also noticed this popping up sometimes:
{code}
Found 0 received and 0 filtered routes.
Query took 1.18 ms to complete.
Routes cache was built 2020 years ago and is currently being refreshed.
{code}

**Comment by stefanplug** [comment]
Might be related to issue #22

**Comment by stefanplug** [comment]
I think the issue is that the search cache gets cleared every 5 minutes, but 5 minutes isn't enough to even load all of our rsses (40). when it refreshes it starts again empty from scratch and will never reach the remaining rsses before the next cache clear.

Would it be possible to somehow make this a rolling process? so instead of a cache clear every 5 minutes to be able to say if just start again from the first rs if you reached the last rs?

**Comment by annikahannig** [comment]
Hej! Thanks! I'll look into it...
In theory, the routes store should keep the old routes data before replacing it with the new dump after the refresh...
