### ISSUE TITLE
Link to irrexplorer "/search" no longer valid

### ISSUE THREAD

**Issue by bluikko** [alice-lg/alice-lg#78]
Looking at routes sent by a peer, the AS-path has each ASN a clickable link that takes to IRR explorer. But IRR explorer has discontinued the `/search` endpoint - all the links in Alice-LG should be updated from:
http://irrexplorer.nlnog.net/search/$ASN
To:
https://irrexplorer.nlnog.net/asn/$ASN
Example of new valid link:
https://irrexplorer.nlnog.net/asn/112

The protocol should also be changed from http to https.

**Comment by annikahannig** [comment]
Thanks for finding out the new URL!

I'm currently preparing a release with the new OpenBGPd support, and I try to add this fix to it :)
