### ISSUE TITLE
timezone configuration broken

### ISSUE THREAD

**Issue by bluikko** [alice-lg/alice-lg#85]
Edit: I found out in https://github.com/alice-lg/alice-lg/blob/master/etc/alice-lg/alice.example.conf an example for the timezone (`Europe/Brussels`) - even this setting fails. So I can only suspect that the whole timezone configuration is broken currently.

The `README.md` has an example for setting a time zone:
```
# timezone = UTC
```

And indeed setting the `timezone` to `UTC` works. But I could not get any other setting to work. The syntax for this configuration parameter should be documented.  
Formats tested and not working:
- `GMT+2`
- `GMT+2:00`
- `PST`
- `EET`
- `UTC+2`
- `UTC+2:00`
- `Paris`
- `Europe/Paris`
- `europe/paris`
- `Europe_Paris`
- `+2`
- `2`
- `120`
- `+120`
- `paris`

All of them result in error like `with: unknown time zone EET - NEXT STATE: ERROR`.

Either the `timezone` configuration parameter does not work at all __and should be removed from README.md__; or it is using some convoluted format that I cannot figure out __and should be documented__.

Edit: it is obvious that the timezone configuration is broken since the example configuration does not work either.

**Comment by annikahannig** [comment]
It's not broken.

> if the name is "" or "UTC", LoadLocation returns UTC. If the name is "Local", LoadLocation returns Local.
> Otherwise, the name is taken to be a location name corresponding to a file in the IANA Time Zone database, such as "America/New_York".

**Comment by bluikko** [comment]
It is broken on the Docker image.

Even the setting in the example configuration file `Europe/Brussels' does not work: `unknown time zone Europe/Brussels - NEXT STATE: ERROR`

The Docker image is missing time zone data?

**Comment by bluikko** [comment]
> It's not broken.
> 
> > if the name is "" or "UTC", LoadLocation returns UTC. If the name is "Local", LoadLocation returns Local.
> > Otherwise, the name is taken to be a location name corresponding to a file in the IANA Time Zone database, such as "America/New_York".

Where is this documentation? I did not find anything else besides the example configuration file so I guess it is from the o source files?
