### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by fenggolang** [alice-lg/alice-lg#95]
![image](https://user-images.githubusercontent.com/16982786/174763399-3f05cbcf-9cc3-4b9f-920a-3241572a3d3e.png)
[root@harbor alice-lg]# make
go test ./pkg/...
client/assets.go:11:12: pattern build/*: no matching files found
make: *** [backend_tests] Error 1
[root@harbor alice-lg]#

**Comment by annikahannig** [comment]
looks like the UI has to be built before running the tests.

As setting up the node build stuff is a bit painful, I suggest using docker for now.

`make -f Makefile.docker`

**Comment by annikahannig** [comment]
(or podman for what it's worth. `make -f Makefile.docker DOCKER=podman`)

**Comment by annikahannig** [comment]
The next milestone is actually modernizing the UI and the UI build process. However this might still take a couple of month.

**Comment by fenggolang** [comment]
ok
