### ISSUE TITLE
Alice Crashes with generic extended community on OpenBGPd Route-Server.

### ISSUE THREAD

**Issue by moshivji** [alice-lg/alice-lg#99]
We have had an issue where both our Alice Looking Glasses crashed when they received data from Open-BGPd-state-server for a peer that had a generic extended community tagged to their prefixes. The same community on BIRD route-servers seemed to be handled okay with Alice and did not crash.

An example of one of the prefixes on our OpenbGPd route-server shows the community as

```
BGP routing table entry for 115.84.76.0/24
    24482 24482 45430 9873
    Nexthop 195.66.246.16 (via 195.66.246.16) Neighbor 195.66.246.16 (124.6.36.1)
    Origin IGP, metric 185022, localpref 100, weight 0, ovs valid, external, valid
    Last update: 00:02:12 ago
    Communities: 8714:65010 8714:65012
    Ext. Communities: [0] 0x8000000000000000
```

On BIRD the same prefix shows

```
115.84.76.0/24     via 195.66.246.16 on eno2 [R195.66.246.16 2022-08-09 19:25:21] (100) [AS9873i]
    Type: BGP unicast univ
    BGP.origin: IGP
    BGP.as_path: 24482 24482 45430 9873
    BGP.next_hop: 195.66.246.16
    BGP.med: 185022
    BGP.local_pref: 100
    BGP.community: (7613,1113) (8714,8714) (9741,1113) (9873,50539) (45430,2111) (45458,2117) (65131,9931) (65131,25386) (65131,45458) (65131,45788) (65231,9741) (65331,7613) (65431,17499)
    BGP.ext_community: (generic, 0x80000000, 0x10000)
```

And Alice displays that as it shows in the CLI.

A trace at the time when Alice refreshed and picked up the peer showed

```
Aug 10 17:32:07 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[45039]: panic: runtime error: index out of range [0] with length 0
Aug 10 17:32:07 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[45039]: github.com/alice-lg/alice-lg/pkg/sources/openbgpd.decodeExtendedCommunities({0x96dc40, 0xc0ae1d72c0})
```

Once the peer scrubbed of the communities AliceLG remained stable.

**Comment by annikahannig** [comment]
Can you maybe add the structured output (`bgpctl -j`) for the peer?

**Comment by moshivji** [comment]
[output.txt](https://github.com/alice-lg/alice-lg/files/9337011/output.txt)
[output2.txt](https://github.com/alice-lg/alice-lg/files/9337016/output2.txt)

Hi
These are attached.
Not that the prefixes with customers ext communities are no longer tagged by the peer.

Regards
Mo

**Comment by annikahannig** [comment]
I see, the ext communities are missing in the structured output.
To see what the parsing issue is, I would however need this :(

**Comment by moshivji** [comment]
Okay I need to work with the peer to get this without taking the LG servers down again.
I will come up to you at some point with this information.

Mo

**Comment by annikahannig** [comment]
Okay - thanks :)
I know this pretty inconvenient - maybe the issue can be reproduced in a lab environment?

**Comment by moshivji** [comment]
Yeah I have tried to do this in ExaBGP in our lab but I get errors when running so either it can not handle that kind of extended community or my version of ExaBGP needs upgrading.

**Comment by annikahannig** [comment]
So, I'm pretty much running out of ideas to try.

The expected output of the bgpctl command should be something along the lines of

```
"extended_communities": [
        "[0] 0x8000000000000000"
]                             
```
At least this is the result of a quick test program using the bgpctl source.
```
int main() {                                                                
    uint8_t data[] = { 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };    
    json_do_ext_community(data, 8);                                         
                                                                            
    return 0;                                                               
}                                                                           
```

When i feed this into `decodeExtendedCommunities`, the decoder just returns an empty list, because decoding this format is not yet supported. However: it does not crash.

Also I deliberately tried to crash the decoder with all kinds of unknown formats, without any luck.

Can you still reproduce the issue?

**Comment by moshivji** [comment]
Sorry for the delayed reply. We have had another similar issue with this the deploying a new OpenBGPd server.

We have had Alice crash when it has collected data from the OpenBGPd-State-Server for prefixes tagged with the following Extended Communities and subtypes.

    Ext. Communities: soo 169.45.17.71:1
    Ext. Communities: soo 169.45.17.71:1
    Ext. Communities: soo 169.45.17.73:1
    Ext. Communities: soo 169.45.17.73:1
    Ext. Communities: soo 169.45.17.75:1
    Ext. Communities: soo 169.45.17.75:1
 Once we remove the peer that was announcing the prefixes being announced with those communities Alice remained stable.

Here are some outputs from journalctl around the time Alice crashed ,

`Feb 15 03:25:36 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]: 2023/02/15 03:25:36 Freeing memory
Feb 15 03:26:19 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]: 2023/02/15 03:26:19 API ERROR :: RS4.LON2 (IPv4).neighbors() :: json: cannot unmarshal string into Go value of type map[string]interface {}
Feb 15 03:26:22 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]: 2023/02/15 03:26:22 API ERROR :: RS4.LON2 (IPv4).neighbors() :: json: cannot unmarshal string into Go value of type map[string]interface {}
Feb 15 03:26:23 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]: 2023/02/15 03:26:23 API ERROR :: RS4.LON2 (IPv4).neighbors() :: json: cannot unmarshal string into Go value of type map[string]interface {}
Feb 15 03:26:25 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]: 2023/02/15 03:26:25 API ERROR :: RS4.LON2 (IPv4).neighbors() :: json: cannot unmarshal string into Go value of type map[string]interface {}
Feb 15 03:26:39 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]: 2023/02/15 03:26:39 API ERROR :: RS4.LON2 (IPv4).neighbors() :: json: cannot unmarshal string into Go value of type map[string]interface {}
Feb 15 03:27:09 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]: panic: runtime error: index out of range [0] with length 0
Feb 15 03:27:09 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]: goroutine 18 [running]:
Feb 15 03:27:09 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]: github.com/alice-lg/alice-lg/pkg/sources/openbgpd.decodeExtendedCommunities({0x96dc40, 0xc20079f440})
Feb 15 03:27:09 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]:         /linx/go/src/github.com/alice-lg/alice-lg/pkg/sources/openbgpd/decoders.go:236 +0x2ed
Feb 15 03:27:09 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]: github.com/alice-lg/alice-lg/pkg/sources/openbgpd.decodeRoute(0xc20081fb60)
Feb 15 03:27:09 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]:         /linx/go/src/github.com/alice-lg/alice-lg/pkg/sources/openbgpd/decoders.go:167 +0x453
Feb 15 03:27:09 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]: github.com/alice-lg/alice-lg/pkg/sources/openbgpd.decodeRoutes({0x9a8120, 0xc20081ec90})
Feb 15 03:27:09 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]:         /linx/go/src/github.com/alice-lg/alice-lg/pkg/sources/openbgpd/decoders.go:136 +0x19a
Feb 15 03:27:09 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]: github.com/alice-lg/alice-lg/pkg/sources/openbgpd.(*StateServerSource).RoutesFiltered(0xc01e681740, {0xc1ffaba570, 0x14})
Feb 15 03:27:09 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]:         /linx/go/src/github.com/alice-lg/alice-lg/pkg/sources/openbgpd/state_server_source.go:337 +0xc6
Feb 15 03:27:09 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]: github.com/alice-lg/alice-lg/pkg/sources/openbgpd.(*StateServerSource).Neighbours(0xc01e681740)
Feb 15 03:27:09 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]:         /linx/go/src/github.com/alice-lg/alice-lg/pkg/sources/openbgpd/state_server_source.go:177 +0x1a5
Feb 15 03:27:09 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]: github.com/alice-lg/alice-lg/pkg/backend.(*NeighboursStore).update(0xc0000c5b00)
Feb 15 03:27:09 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]:         /linx/go/src/github.com/alice-lg/alice-lg/pkg/backend/neighbours_store.go:122 +0x20e
Feb 15 03:27:09 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]: github.com/alice-lg/alice-lg/pkg/backend.(*NeighboursStore).init(0xc0000c5b00)
Feb 15 03:27:09 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]:         /linx/go/src/github.com/alice-lg/alice-lg/pkg/backend/neighbours_store.go:83 +0x45
Feb 15 03:27:09 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]: created by github.com/alice-lg/alice-lg/pkg/backend.(*NeighboursStore).Start
Feb 15 03:27:09 alice1-rs-tch-u.linx.net alice-lg-linux-amd64[186891]:         /linx/go/src/github.com/alice-lg/alice-lg/pkg/backend/neighbours_store.go:70 +0xef
Feb 15 03:27:09 alice1-rs-tch-u.linx.net systemd[1]: alice-lg.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 15 03:27:09 alice1-rs-tch-u.linx.net systemd[1]: alice-lg.service: Failed with result 'exit-code'.
`

**Comment by moshivji** [comment]
Hi

It seems we have had another crash related to some prefixes having the type generic communities tagged.

Our BIRD RS shows an example of a prefix with with the offending extended community type:



```
bird> show route 198.207.195.0/24 all
198.207.195.0/24   via 195.66.239.188 on eno1 [R195.66.239.188 2022-07-19 23:31:44] * (100) [AS7381i]
	Type: BGP unicast univ
	BGP.origin: IGP
	BGP.as_path: 1828 7381
	BGP.next_hop: 195.66.239.188
	BGP.local_pref: 100
	BGP.community: (1828,31999) (7381,10105) (7381,11006) (1828,30) (1828,31110) (8714,65010) (8714,65023) (8714,65011)
	BGP.ext_community: (generic, 0x3060000, 0x500)
	BGP.large_community: (8714, 1001, 2) (8714, 1000, 2) (8714, 1001, 1)

```

The equivalent on OpenBGPd shows:

```
BGP routing table entry for 198.207.195.0/24
    1828 7381
    Nexthop 195.66.239.188 (via 195.66.237.230) Neighbor 195.66.239.188 (50.115.89.111)
    Origin IGP, metric 0, localpref 100, weight 0, ovs not-found, external, valid, best
    Last update: 02:50:18 ago
    Communities: 8714:65010 8714:65011 8714:65023
    Ext. Communities: ort 0x500

```

Unfortunately I can not re-create this in my lab as ExaBGP does not support this type of community.

**Comment by moshivji** [comment]
@annikahannig , I have. noticed we still use Alice 5.0.0, was your testing done on Alice 6.0.0 ?

**Comment by moshivji** [comment]
Apologies for the late reply. I do not think this was an issue with Alice but and issue with OpenBGPd sending a [bad community ](https://www.rssf.nl/post/openbgpd-8-3-released).

We have upgraded to version6 for now and all seems good so far.

**Comment by annikahannig** [comment]
Good to hear :)

Thanks for the info!
